openapi: 3.0.0
info:
  title: Delete Cloud Storage Bucket
  version: 1.0.0
  description: HTTP Cloud Function to delete a Cloud Storage bucket.

servers:
  - url: https://delete-bucket-255325954302.us-central1.run.app  # URL of the Cloud Run function

paths:
  /:
    delete:
      summary: Delete a Cloud Storage bucket
      operationId: deleteBucket
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - project
                - bucket_name
              properties:
                project:
                  type: string
                  description: Google Cloud project ID.
                  example: my-gcp-project
                bucket_name:
                  type: string
                  description: Name of the Cloud Storage bucket to delete.
                  example: bucket08881

      responses:
        '200':
          description: Cloud Storage bucket deleted successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Confirmation message.
                    example: "Bucket 'bucket08881' deleted successfully in project 'my-gcp-project'."
        '400':
          description: Bad Request - Missing or invalid input.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message indicating the reason for the failure.
                    example: "Missing required fields: project, bucket_name"
        '404':
          description: Not Found - Bucket does not exist.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message indicating that the bucket does not exist.
                    example: "Bucket 'bucket08881' not found."
        '500':
          description: Internal Server Error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message indicating the reason for the failure.
                    example: "An unexpected error occurred."

components:
  schemas: {}
